# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CV Julio

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Build Angular
        run: |
          npx ng build --configuration production --base-href "/julio-presentation/"
          # Si tu salida es dist/cv_julio/browser, ajusta el directorio en el paso de deploy

      - name: Add 404 fallback for SPA
        run: |
          if [ -f dist/cv_julio/index.html ]; then cp dist/cv_julio/index.html dist/cv_julio/404.html; fi
          if [ -f dist/cv_julio/browser/index.html ]; then cp dist/cv_julio/browser/index.html dist/cv_julio/browser/404.html; fi

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/cv_julio/browser
